# Assignment TREND

In [29]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # Show all columns when printing a dataframe

In [37]:
uro = pd.read_excel('/home/jlaw/projects/python/roboAdvisorSystTrading/notebooks/data/assignment_TREND_data.xlsx', header=1, sheet_name='uro')

# fill out the moving average cols using daily percent change PC(%)
uro['ma10'] = uro['PC(%)'].rolling(window=10).mean()
uro['ma30'] = uro['PC(%)'].rolling(window=30).mean()
uro['ma80'] = uro['PC(%)'].rolling(window=80).mean()
uro['ma100'] = uro['PC(%)'].rolling(window=100).mean()
uro['ma160'] = uro['PC(%)'].rolling(window=160).mean()

# fill out the return cols Ret10/30	Ret30/100 Ret80/160 starting at 0 position, then +1 when short term MA is above long term MA, -1 when short term MA is below long term MA
# actually want to multiply the 0/1/-1 by daily percent change of next day (recognize signal EOD, trade next day EOD)
uro['Ret10/30'] = 0
uro['Ret30/100'] = 0
uro['Ret80/160'] = 0
uro.loc[uro['ma10'] > uro['ma30'], 'Ret10/30'] = 1
uro.loc[uro['ma10'] < uro['ma30'], 'Ret10/30'] = -1
uro.loc[uro['ma30'] > uro['ma100'], 'Ret30/100'] = 1
uro.loc[uro['ma30'] < uro['ma100'], 'Ret30/100'] = -1
uro.loc[uro['ma80'] > uro['ma160'], 'Ret80/160'] = 1
uro.loc[uro['ma80'] < uro['ma160'], 'Ret80/160'] = -1
uro['Ret10/30'] = uro['Ret10/30'].shift(1) * uro['PC(%)'] / 100
uro['Ret30/100'] = uro['Ret30/100'].shift(1) * uro['PC(%)'] / 100
uro['Ret80/160'] = uro['Ret80/160'].shift(1) * uro['PC(%)'] / 100

# fill out the 

uro.head(40)

,#Date,Open,High,Low,Close,NC,PC(%),Roll,100,ma10,ma30,ma80,ma100,ma160,Ret10/30,Ret30/100,Ret80/160,Hi30,Low30,action,position,BrkRet30,Unnamed: 22,TenThirty,Thirty 100,Eigthy 160,Brkout30
0,19990308.0,1.0958,1.0961,1.0933,1.0943,0.0000,0.000000,0.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TenThirty,1.0,NaN,NaN,NaN
1,19990309.0,1.0925,1.0956,1.0916,1.0944,0.0001,0.009138,0.0,100.009138,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Thirty 100,NaN,1.0,NaN,NaN
2,19990310.0,1.1010,1.1025,1.0990,1.1006,0.0062,0.566520,0.0,100.575710,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Eigthy 160,NaN,NaN,1.0,NaN
3,19990311.0,1.0933,1.1115,1.0852,1.1084,0.0078,0.708704,0.0,101.288495,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,Brkout30,NaN,NaN,NaN,1.0
4,19990312.0,1.0962,1.1011,1.0945,1.0957,-0.0127,-1.145796,0.0,100.127936,NaN,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,19990315.0,1.0993,1.1009,1.0970,1.0989,0.0032,0.292051,0.0,100.420360,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,19990316.0,1.0960,1.1058,1.0946,1.1051,0.0062,0.564201,0.0,100.986932,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,19990317.0,1.1012,1.1095,1.1005,1.1055,0.0004,0.036196,0.0,101.023485,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19990318.0,1.1059,1.1092,1.1012,1.1021,-0.0034,-0.307553,0.0,100.712784,NaN,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,19990319.0,1.0957,1.0983,1.0931,1.0938,-0.0083,-0.753108,0.0,99.954309,-0.002965,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,19990322.0,1.0916,1.0967,1.0905,1.0964,0.0026,0.237703,0.0,100.191903,0.020806,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,19990323.0,1.0945,1.0974,1.0913,1.0958,-0.0006,-0.054725,0.0,100.137074,0.014419,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,19990324.0,1.0980,1.1012,1.0927,1.0942,-0.0016,-0.146012,0.0,99.990862,-0.056834,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,19990325.0,1.0940,1.0951,1.0880,1.0883,-0.0059,-0.539207,0.0,99.451704,-0.181625,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,19990326.0,1.0851,1.0851,1.0760,1.0813,-0.0070,-0.643205,0.0,98.812026,-0.131366,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,19990329.0,1.0752,1.0785,1.0733,1.0784,-0.0029,-0.268196,0.0,98.547016,-0.187391,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,19990330.0,1.0780,1.0820,1.0755,1.0762,-0.0022,-0.204006,0.0,98.345975,-0.264211,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,19990331.0,1.0805,1.0869,1.0795,1.0802,0.0040,0.371678,0.0,98.711505,-0.230663,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19990401.0,1.0842,1.0864,1.0810,1.0833,0.0031,0.286984,0.0,98.994791,-0.171209,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19990402.0,1.0842,1.0864,1.0810,1.0833,0.0000,0.000000,0.0,98.994791,-0.095898,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,19990405.0,1.0796,1.0796,1.0746,1.0756,-0.0077,-0.710791,0.0,98.291145,-0.190748,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,19990406.0,1.0774,1.0900,1.0747,1.0884,0.0128,1.190033,0.0,99.460843,-0.066272,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,19990407.0,1.0846,1.0850,1.0810,1.0816,-0.0068,-0.624770,0.0,98.839441,-0.114148,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,19990408.0,1.0870,1.0915,1.0768,1.0784,-0.0032,-0.295858,0.0,98.547016,-0.089813,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,19990409.0,1.0829,1.0856,1.0814,1.0845,0.0061,0.565653,0.0,99.104450,0.031073,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,19990412.0,1.0907,1.0921,1.0865,1.0866,0.0021,0.193638,0.0,99.296354,0.077256,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,19990413.0,1.0805,1.0842,1.0795,1.0811,-0.0055,-0.506166,0.0,98.793749,0.047040,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,19990414.0,1.0835,1.0855,1.0821,1.0838,0.0027,0.249746,0.0,99.040483,0.034847,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,19990415.0,1.0820,1.0829,1.0730,1.0742,-0.0096,-0.885772,0.0,98.163209,-0.082429,NaN,NaN,NaN,NaN,-0.000000,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,19990416.0,1.0704,1.0755,1.0703,1.0753,0.0011,0.102402,0.0,98.263730,-0.072189,-0.057017,NaN,NaN,NaN,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,19990419.0,1.0672,1.0687,1.0632,1.0671,-0.0082,-0.762578,0.0,97.514393,-0.077367,-0.082437,NaN,NaN,NaN,0.007626,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,19990420.0,1.0684,1.0712,1.0648,1.0664,-0.0007,-0.065598,0.0,97.450425,-0.202930,-0.084928,NaN,NaN,NaN,-0.000656,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,19990421.0,1.0621,1.0664,1.0616,1.0656,-0.0008,-0.075019,0.0,97.377319,-0.147955,-0.106312,NaN,NaN,NaN,0.000750,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,19990422.0,1.0598,1.0652,1.0598,1.0650,-0.0006,-0.056306,0.0,97.322489,-0.124000,-0.131813,NaN,NaN,NaN,0.000563,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,19990423.0,1.0673,1.0702,1.0630,1.0646,-0.0004,-0.037559,0.0,97.285936,-0.184321,-0.094871,NaN,NaN,NaN,-0.000376,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,19990426.0,1.0646,1.0653,1.0612,1.0619,-0.0027,-0.253616,0.0,97.039203,-0.229047,-0.113060,NaN,NaN,NaN,0.002536,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,19990427.0,1.0661,1.0701,1.0654,1.0698,0.0079,0.743950,0.0,97.761126,-0.104035,-0.107069,NaN,NaN,NaN,-0.007439,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,19990428.0,1.0697,1.0713,1.0638,1.0655,-0.0043,-0.401944,0.0,97.368181,-0.169204,-0.121673,NaN,NaN,NaN,-0.004019,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,19990429.0,1.0644,1.0653,1.0604,1.0621,-0.0034,-0.319099,0.0,97.057480,-0.112537,-0.122058,NaN,NaN,NaN,0.003191,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,19990430.0,1.0621,1.0650,1.0580,1.0613,-0.0008,-0.075322,0.0,96.984374,-0.130309,-0.099465,NaN,NaN,NaN,-0.000753,-0.0,-0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
sp = pd.read_excel('/home/jlaw/projects/python/roboAdvisorSystTrading/notebooks/data/assignment_TREND_data.xlsx', header=1, sheet_name='sp')

sp['ma10'] = sp['PC(%)'].rolling(window=10).mean()
sp['ma30'] = sp['PC(%)'].rolling(window=30).mean()
sp['ma80'] = sp['PC(%)'].rolling(window=80).mean()
sp['ma100'] = sp['PC(%)'].rolling(window=100).mean()
sp['ma160'] = sp['PC(%)'].rolling(window=160).mean()

sp.head()

,#Date,Open,High,Low,Close,NC,PC(%),Roll,100,ma10,ma30,ma80,ma100,ma160,Ret10/30,Ret30/100,Ret80/160,Hi30,Low30,action,position,BrkRet30,Unnamed: 22,TenThirty,Thirty 100,Eigthy 160,Brkout30
0,19990308.0,1279.0,1285.40002,1272.59998,1283.30005,4.80005,0.375444,0.0,100.375444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TenThirty,1.0,NaN,NaN,NaN
1,19990309.0,1280.0,1296.19995,1275.50000,1279.80005,-3.50000,-0.272734,0.0,100.101685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thirty 100,NaN,1.0,NaN,NaN
2,19990310.0,1282.0,1289.90002,1275.69995,1289.00000,9.19995,0.718858,0.0,100.821275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eigthy 160,NaN,NaN,1.0,NaN
3,19990311.0,1291.0,1309.00000,1285.00000,1304.50000,15.50000,1.202483,12.5,102.033633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brkout30,NaN,NaN,NaN,1.0
4,19990312.0,1320.0,1320.19995,1301.50000,1303.80005,-13.19995,-1.002274,0.0,101.010976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
ty = pd.read_excel('/home/jlaw/projects/python/roboAdvisorSystTrading/notebooks/data/assignment_TREND_data.xlsx', header=1, sheet_name='ty')

ty['ma10'] = ty['PC(%)'].rolling(window=10).mean()
ty['ma30'] = ty['PC(%)'].rolling(window=30).mean()
ty['ma80'] = ty['PC(%)'].rolling(window=80).mean()
ty['ma100'] = ty['PC(%)'].rolling(window=100).mean()
ty['ma160'] = ty['PC(%)'].rolling(window=160).mean()

ty.head()

,#Date,Open,High,Low,Close,NC,PC(%),Roll,100,ma10,ma30,ma80,ma100,ma160,Ret10/30,Ret30/100,Ret80/160,Hi30,Low30,action,position,BrkRet30,Unnamed: 22,TenThirty,Thirty 100,Eigthy 160,Brkout30
0,19990308.0,114.46875,114.68750,114.37500,114.43750,0.09375,0.081990,0.0,100.081990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TenThirty,1.0,NaN,NaN,NaN
1,19990309.0,114.25000,115.12500,114.12500,115.00000,0.56250,0.491535,0.0,100.573927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thirty 100,NaN,1.0,NaN,NaN
2,19990310.0,115.03125,115.12500,114.68750,114.87500,-0.12500,-0.108696,0.0,100.464608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Eigthy 160,NaN,NaN,1.0,NaN
3,19990311.0,114.78125,115.09375,114.62500,114.87500,0.00000,0.000000,0.0,100.464608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brkout30,NaN,NaN,NaN,1.0
4,19990312.0,114.93750,115.21875,114.90625,115.15625,0.28125,0.244831,0.0,100.710577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN